server:
  servlet:
    context-path: /api/v1/
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 600m
      cookie:
        name: JSESSIONID
        secure: true
        http-only: true
        max-age: 600m
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: true

spring:
  config:
    import: optional:configserver:https://cloud.seoeungi.work
  data:
    web:
      pageable:
        one-indexed-parameters: true
  cloud:
    config:
      name: planverse
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: none
    health:
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  config: classpath:spring-logback.xml
  level:
    _org:
      springframework:
        web:
          servlet:
            HandlerMapping:
              Mappings: OFF
    org:
      mybatis:
        spring:
          SqlSessionFactoryBean: OFF
          mapper:
            ClassPathMapperScanner: OFF
      hibernate:
        internal:
          SessionFactoryImpl: OFF
        bytecode:
          internal:
            bytebuddy:
              BytecodeProviderImpl: OFF
        jpa:
          event:
            internal:
              CallbackDefinitionResolverLegacyImpl: OFF
        type:
          BasicTypeRegistry: OFF
        validator:
          internal:
            xml:
              config:
                ResourceLoaderHelper: OFF
            engine:
              ValidatorFactoryConfigurationHelper: OFF
        mapping:
          PrimaryKey: OFF
          BasicValue: OFF
        orm:
          sql:
            ast:
              create: OFF
          model:
            mapping:
              creation: OFF
          idgen:
            factory: OFF
        persister:
          entity:
            AbstractEntityPersister: OFF
        query:
          named:
            NamedObjectRepository: OFF
          sqm:
            function:
              SqmFunctionRegistry: OFF
        boot:
          registry:
            classloading:
              internal:
                ClassLoaderServiceImpl: OFF
          internal:
            ClassLoaderAccessImpl: OFF
          model:
            internal:
              BinderHelper: OFF
              EntityBinder: OFF
              AnnotatedColumn: OFF
              AbstractPropertyHolder: OFF
              PropertyBinder: OFF
              BasicValueBinder: OFF
        HQL_FUNCTIONS: OFF
        resource:
          transaction:
            backend:
              jdbc:
                internal:
                  JdbcResourceLocalTransactionCoordinatorImpl: INFO
      springframework:
        boot:
          context:
            properties:
              source:
                ConfigurationPropertySourcesPropertyResolver: OFF
        core:
          env:
            PropertySourcesPropertyResolver: OFF
        orm:
          jpa:
            SharedEntityManagerCreator: OFF
        beans:
          CachedIntrospectionResults: OFF
          factory:
            support:
              DefaultListableBeanFactory: OFF
        data:
          jpa:
            repository:
              query:
                NamedQuery: OFF
          convert:
            CustomConversions: OFF
          repository:
            core:
              support:
                RepositoryFactorySupport: OFF
            config:
              RepositoryComponentProvider: OFF
        context:
          annotation:
            ClassPathBeanDefinitionScanner: OFF
        session:
          web:
            http:
              SessionRepositoryFilter:
                SESSION_LOGGER: INFO

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 10000
    pool-size: 1